### ISSUE TITLE
"panic: unknown field" error with x/layer2 network properties

### ISSUE THREAD

**Issue by kmlbgn** [KiraCore/sekai#477]
Getting these errors with layer2 module 

cc. @MrLutik 

```bash
WARNING: Nothing running on port 26658, or failed to kill processes
+ EXIT_CODE=0
+ sekaid start --home=/root/.sekai --trace
6:42PM INF starting node with ABCI Tendermint in-process
6:42PM INF service start impl=multiAppConn module=proxy msg={}
6:42PM INF service start connection=query impl=localClient module=abci-client msg={}
6:42PM INF service start connection=snapshot impl=localClient module=abci-client msg={}
6:42PM INF service start connection=mempool impl=localClient module=abci-client msg={}
6:42PM INF service start connection=consensus impl=localClient module=abci-client msg={}
6:42PM INF service start impl=EventBus module=events msg={}
6:42PM INF service start impl=PubSub module=pubsub msg={}
6:42PM INF service start impl=IndexerService module=txindex msg={}
6:42PM INF ABCI Handshake App Info hash= height=0 module=consensus protocol-version=0 software-version=v0.3.13.37
6:42PM INF ABCI Replay Blocks appHeight=0 module=consensus stateHeight=0 storeHeight=0
panic: unknown field "dapp_inactive_rank_decrease_percent" in types.NetworkProperties

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/codec.(*ProtoCodec).MustUnmarshalJSON(0x24264f0?, {0xc000d98600?, 0x7fe4b03b98c0?, 0xc000ee68f0?}, {0x242ad28?, 0xc00001bd10?})
	/home/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.10/codec/proto_codec.go:178 +0x45
github.com/KiraCore/sekai/x/gov.AppModule.InitGenesis({{}, {{_, _}, {_, _}, {_, _}, {_}}}, {{0x243b300, 0xc000134020}, ...}, ...)
	/__w/sekai/sekai/x/gov/module.go:90 +0xc2
github.com/cosmos/cosmos-sdk/types/module.(*Manager).InitGenesis(_, {{0x243b300, 0xc000134020}, {0x2448280, 0xc000ee06c0}, {{0x0, 0x0}, {0xc0012fa0e0, 0xa}, 0x0, ...}, ...}, ...)
	/home/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.10/types/module/module.go:327 +0x29d
github.com/KiraCore/sekai/app.(*SekaiApp).InitChainer(_, {{0x243b300, 0xc000134020}, {0x2448280, 0xc000ee06c0}, {{0x0, 0x0}, {0xc0012fa0e0, 0xa}, 0x0, ...}, ...}, ...)
	/__w/sekai/sekai/app/app.go:545 +0x137
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).InitChain(0xc0001cf500, {{0x9878ec1, 0xedbe822bb, 0x0}, {0xc0012fa0e0, 0xa}, 0xc00028df80, {0x32432b8, 0x0, 0x0}, ...})
	/home/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.10/baseapp/abci.go:63 +0x455
github.com/tendermint/tendermint/abci/client.(*localClient).InitChainSync(0xc001104f00, {{0x9878ec1, 0xedbe822bb, 0x0}, {0xc0012fa0e0, 0xa}, 0xc00028df80, {0x32432b8, 0x0, 0x0}, ...})
	/home/go/pkg/mod/github.com/tendermint/tendermint@v0.34.22/abci/client/local_client.go:272 +0x118
github.com/tendermint/tendermint/proxy.(*appConnConsensus).InitChainSync(0x0?, {{0x9878ec1, 0xedbe822bb, 0x0}, {0xc0012fa0e0, 0xa}, 0xc00028df80, {0x32432b8, 0x0, 0x0}, ...})
	/home/go/pkg/mod/github.com/tendermint/tendermint@v0.34.22/proxy/app_conn.go:77 +0x55
github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(_, {{{0xb, 0x0}, {0x1b44444, 0x7}}, {0xc0012fa0e0, 0xa}, 0x1, 0x0, {{0x0, ...}, ...}, ...}, ...)
	/home/go/pkg/mod/github.com/tendermint/tendermint@v0.34.22/consensus/replay.go:319 +0xd78
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc000d7ddf0, {0x24488b8, 0xc000ec6dd0})
	/home/go/pkg/mod/github.com/tendermint/tendermint@v0.34.22/consensus/replay.go:268 +0x3c8
github.com/tendermint/tendermint/node.doHandshake({_, _}, {{{0xb, 0x0}, {0x1b44444, 0x7}}, {0xc0012fa0e0, 0xa}, 0x1, 0x0, ...}, ...)
	/home/go/pkg/mod/github.com/tendermint/tendermint@v0.34.22/node/node.go:330 +0x1b8
github.com/tendermint/tendermint/node.NewNode(0xc000244640, {0x24383a8, 0xc000e87d60}, 0xc000e94820, {0x2421240, 0xc000127398}, 0x0?, 0x0?, 0xc000e94a80, {0x243cb80, ...}, ...)
	/home/go/pkg/mod/github.com/tendermint/tendermint@v0.34.22/node/node.go:778 +0x597
github.com/cosmos/cosmos-sdk/server.startInProcess(_, {{0x0, 0x0, 0x0}, {0x244f0f0, 0xc000e84f00}, {0x0, 0x0}, {0x2440af8, 0xc0010c9b50}, ...}, ...)
	/home/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.10/server/start.go:280 +0x7db
github.com/cosmos/cosmos-sdk/server.StartCmd.func2(0xc00106fb80?, {0xc000e41080?, 0x0?, 0x2?})
	/home/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.10/server/start.go:128 +0x169
github.com/spf13/cobra.(*Command).execute(0xc00106fb80, {0xc000e41060, 0x2, 0x2})
	/home/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:872 +0x694
github.com/spf13/cobra.(*Command).ExecuteC(0xc000cf8000)
	/home/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
	/home/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	/home/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:911
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0x0?, {0xc00107f690, 0xd})
	/home/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.10/server/cmd/execute.go:36 +0x1eb
main.main()
	/__w/sekai/sekai/cmd/sekaid/main.go:185 +0x31
+ EXIT_CODE=2
+ set +x
ERROR: SEKAID process failed with the exit code 2
+ echoWarn 'WARNING: validator is still being configured, please wait ...'
+ echo -e '\e[0m\e[33;1mWARNING: validator is still being configured, please wait ...\e[0m'
```

```bash
WARNING: Nothing running on port 26658, or failed to kill processes
+ EXIT_CODE=0
+ sekaid start --home=/root/.sekai --trace
6:43PM INF starting node with ABCI Tendermint in-process
6:43PM INF service start impl=multiAppConn module=proxy msg={}
6:43PM INF service start connection=query impl=localClient module=abci-client msg={}
6:43PM INF service start connection=snapshot impl=localClient module=abci-client msg={}
6:43PM INF service start connection=mempool impl=localClient module=abci-client msg={}
6:43PM INF service start connection=consensus impl=localClient module=abci-client msg={}
6:43PM INF service start impl=EventBus module=events msg={}
6:43PM INF service start impl=PubSub module=pubsub msg={}
6:43PM INF service start impl=IndexerService module=txindex msg={}
6:43PM INF ABCI Handshake App Info hash= height=0 module=consensus protocol-version=0 software-version=v0.3.13.37
6:43PM INF ABCI Replay Blocks appHeight=0 module=consensus stateHeight=0 storeHeight=0
panic: unknown field "dapp_pool_slippage_default" in types.NetworkProperties

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/codec.(*ProtoCodec).MustUnmarshalJSON(0x24264f0?, {0xc0001f8600?, 0x7f7b04621cc0?, 0xc000113040?}, {0x242ad28?, 0xc0010e8f00?})
	/home/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.10/codec/proto_codec.go:178 +0x45
github.com/KiraCore/sekai/x/gov.AppModule.InitGenesis({{}, {{_, _}, {_, _}, {_, _}, {_}}}, {{0x243b300, 0xc00005a038}, ...}, ...)
	/__w/sekai/sekai/x/gov/module.go:90 +0xc2
github.com/cosmos/cosmos-sdk/types/module.(*Manager).InitGenesis(_, {{0x243b300, 0xc00005a038}, {0x2448280, 0xc000213180}, {{0x0, 0x0}, {0xc0004f5410, 0xa}, 0x0, ...}, ...}, ...)
	/home/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.10/types/module/module.go:327 +0x29d
github.com/KiraCore/sekai/app.(*SekaiApp).InitChainer(_, {{0x243b300, 0xc00005a038}, {0x2448280, 0xc000213180}, {{0x0, 0x0}, {0xc0004f5410, 0xa}, 0x0, ...}, ...}, ...)
	/__w/sekai/sekai/app/app.go:545 +0x137
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).InitChain(0xc000da1340, {{0x9878ec1, 0xedbe822bb, 0x0}, {0xc0004f5410, 0xa}, 0xc00117c120, {0x32432b8, 0x0, 0x0}, ...})
	/home/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.10/baseapp/abci.go:63 +0x455
github.com/tendermint/tendermint/abci/client.(*localClient).InitChainSync(0xc000d05ec0, {{0x9878ec1, 0xedbe822bb, 0x0}, {0xc0004f5410, 0xa}, 0xc00117c120, {0x32432b8, 0x0, 0x0}, ...})
	/home/go/pkg/mod/github.com/tendermint/tendermint@v0.34.22/abci/client/local_client.go:272 +0x118
github.com/tendermint/tendermint/proxy.(*appConnConsensus).InitChainSync(0x0?, {{0x9878ec1, 0xedbe822bb, 0x0}, {0xc0004f5410, 0xa}, 0xc00117c120, {0x32432b8, 0x0, 0x0}, ...})
	/home/go/pkg/mod/github.com/tendermint/tendermint@v0.34.22/proxy/app_conn.go:77 +0x55
github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(_, {{{0xb, 0x0}, {0x1b44444, 0x7}}, {0xc0004f5410, 0xa}, 0x1, 0x0, {{0x0, ...}, ...}, ...}, ...)
	/home/go/pkg/mod/github.com/tendermint/tendermint@v0.34.22/consensus/replay.go:319 +0xd78
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc0012f3df0, {0x24488b8, 0xc00128f860})
	/home/go/pkg/mod/github.com/tendermint/tendermint@v0.34.22/consensus/replay.go:268 +0x3c8
github.com/tendermint/tendermint/node.doHandshake({_, _}, {{{0xb, 0x0}, {0x1b44444, 0x7}}, {0xc0004f5410, 0xa}, 0x1, 0x0, ...}, ...)
	/home/go/pkg/mod/github.com/tendermint/tendermint@v0.34.22/node/node.go:330 +0x1b8
github.com/tendermint/tendermint/node.NewNode(0xc000252500, {0x24383a8, 0xc000d0aa00}, 0xc00105a7f0, {0x2421240, 0xc00000f818}, 0x0?, 0x0?, 0xc00105aa10, {0x243cb80, ...}, ...)
	/home/go/pkg/mod/github.com/tendermint/tendermint@v0.34.22/node/node.go:778 +0x597
github.com/cosmos/cosmos-sdk/server.startInProcess(_, {{0x0, 0x0, 0x0}, {0x244f0f0, 0xc000257980}, {0x0, 0x0}, {0x2440af8, 0xc0010cef90}, ...}, ...)
	/home/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.10/server/start.go:280 +0x7db
github.com/cosmos/cosmos-sdk/server.StartCmd.func2(0xc00111aa00?, {0xc00117d400?, 0x0?, 0x2?})
	/home/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.10/server/start.go:128 +0x169
github.com/spf13/cobra.(*Command).execute(0xc00111aa00, {0xc00117d3e0, 0x2, 0x2})
	/home/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:872 +0x694
github.com/spf13/cobra.(*Command).ExecuteC(0xc000dd1180)
	/home/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
	/home/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	/home/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:911
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0x0?, {0xc0010953a0, 0xd})
	/home/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.10/server/cmd/execute.go:36 +0x1eb
main.main()
	/__w/sekai/sekai/cmd/sekaid/main.go:185 +0x31
+ EXIT_CODE=2
+ set +x
ERROR: SEKAID process failed with the exit code 2
+ echoWarn 'WARNING: validator is still being configured, please wait ...'
+ echo -e '\e[0m\e[33;1mWARNING: validator is still being configured, please wait ...\e[0m'
```

```bash
+ echo -e '\e[0m\e[33;1mWARNING: Nothing running on port 26658, or failed to kill processes\e[0m'
WARNING: Nothing running on port 26658, or failed to kill processes
+ EXIT_CODE=0
+ sekaid start --home=/root/.sekai --trace
6:44PM INF starting node with ABCI Tendermint in-process
6:44PM INF service start impl=multiAppConn module=proxy msg={}
6:44PM INF service start connection=query impl=localClient module=abci-client msg={}
6:44PM INF service start connection=snapshot impl=localClient module=abci-client msg={}
6:44PM INF service start connection=mempool impl=localClient module=abci-client msg={}
6:44PM INF service start connection=consensus impl=localClient module=abci-client msg={}
6:44PM INF service start impl=EventBus module=events msg={}
6:44PM INF service start impl=PubSub module=pubsub msg={}
6:44PM INF service start impl=IndexerService module=txindex msg={}
6:44PM INF ABCI Handshake App Info hash= height=0 module=consensus protocol-version=0 software-version=v0.3.13.37
6:44PM INF ABCI Replay Blocks appHeight=0 module=consensus stateHeight=0 storeHeight=0
panic: unknown field "dapp_mischance_rank_decrease_amount" in types.NetworkProperties

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/codec.(*ProtoCodec).MustUnmarshalJSON(0x24264f0?, {0xc000687900?, 0x7f6f7c0d4c40?, 0xc0001141f0?}, {0x242ad28?, 0xc0010b4690?})
	/home/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.10/codec/proto_codec.go:178 +0x45
github.com/KiraCore/sekai/x/gov.AppModule.InitGenesis({{}, {{_, _}, {_, _}, {_, _}, {_}}}, {{0x243b300, 0xc00005a038}, ...}, ...)
	/__w/sekai/sekai/x/gov/module.go:90 +0xc2
github.com/cosmos/cosmos-sdk/types/module.(*Manager).InitGenesis(_, {{0x243b300, 0xc00005a038}, {0x2448280, 0xc00020fc40}, {{0x0, 0x0}, {0xc00017cab0, 0xa}, 0x0, ...}, ...}, ...)
	/home/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.10/types/module/module.go:327 +0x29d
github.com/KiraCore/sekai/app.(*SekaiApp).InitChainer(_, {{0x243b300, 0xc00005a038}, {0x2448280, 0xc00020fc40}, {{0x0, 0x0}, {0xc00017cab0, 0xa}, 0x0, ...}, ...}, ...)
	/__w/sekai/sekai/app/app.go:545 +0x137
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).InitChain(0xc000030fc0, {{0x9878ec1, 0xedbe822bb, 0x0}, {0xc00017cab0, 0xa}, 0xc000d99e00, {0x32432b8, 0x0, 0x0}, ...})
	/home/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.10/baseapp/abci.go:63 +0x455
github.com/tendermint/tendermint/abci/client.(*localClient).InitChainSync(0xc000dcba40, {{0x9878ec1, 0xedbe822bb, 0x0}, {0xc00017cab0, 0xa}, 0xc000d99e00, {0x32432b8, 0x0, 0x0}, ...})
	/home/go/pkg/mod/github.com/tendermint/tendermint@v0.34.22/abci/client/local_client.go:272 +0x118
github.com/tendermint/tendermint/proxy.(*appConnConsensus).InitChainSync(0x0?, {{0x9878ec1, 0xedbe822bb, 0x0}, {0xc00017cab0, 0xa}, 0xc000d99e00, {0x32432b8, 0x0, 0x0}, ...})
	/home/go/pkg/mod/github.com/tendermint/tendermint@v0.34.22/proxy/app_conn.go:77 +0x55
github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(_, {{{0xb, 0x0}, {0x1b44444, 0x7}}, {0xc00017cab0, 0xa}, 0x1, 0x0, {{0x0, ...}, ...}, ...}, ...)
	/home/go/pkg/mod/github.com/tendermint/tendermint@v0.34.22/consensus/replay.go:319 +0xd78
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc000e51df0, {0x24488b8, 0xc000248c30})
	/home/go/pkg/mod/github.com/tendermint/tendermint@v0.34.22/consensus/replay.go:268 +0x3c8
github.com/tendermint/tendermint/node.doHandshake({_, _}, {{{0xb, 0x0}, {0x1b44444, 0x7}}, {0xc00017cab0, 0xa}, 0x1, 0x0, ...}, ...)
	/home/go/pkg/mod/github.com/tendermint/tendermint@v0.34.22/node/node.go:330 +0x1b8
github.com/tendermint/tendermint/node.NewNode(0xc001047e00, {0x24383a8, 0xc000263ea0}, 0xc00102ae50, {0x2421240, 0xc0005693e0}, 0x0?, 0x0?, 0xc00102b170, {0x243cb80, ...}, ...)
	/home/go/pkg/mod/github.com/tendermint/tendermint@v0.34.22/node/node.go:778 +0x597
github.com/cosmos/cosmos-sdk/server.startInProcess(_, {{0x0, 0x0, 0x0}, {0x244f0f0, 0xc00124e900}, {0x0, 0x0}, {0x2440af8, 0xc0010a27a0}, ...}, ...)
	/home/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.10/server/start.go:280 +0x7db
github.com/cosmos/cosmos-sdk/server.StartCmd.func2(0xc0010d8000?, {0xc001172fe0?, 0x0?, 0x2?})
	/home/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.10/server/start.go:128 +0x169
github.com/spf13/cobra.(*Command).execute(0xc0010d8000, {0xc001172fc0, 0x2, 0x2})
	/home/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:872 +0x694
github.com/spf13/cobra.(*Command).ExecuteC(0xc000dc2780)
	/home/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
	/home/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	/home/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:911
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0x0?, {0xc001035fb0, 0xd})
	/home/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.10/server/cmd/execute.go:36 +0x1eb
main.main()
	/__w/sekai/sekai/cmd/sekaid/main.go:185 +0x31
+ EXIT_CODE=2
+ set +x
ERROR: SEKAID process failed with the exit code 2
+ echoWarn 'WARNING: validator is still being configured, please wait ...'
+ echo -e '\e[0m\e[33;1mWARNING: validator is still being configured, please wait ...\e[0m'
```

```bash
WARNING: Nothing running on port 26658, or failed to kill processes
+ EXIT_CODE=0
+ sekaid start --home=/root/.sekai --trace
6:54PM INF starting node with ABCI Tendermint in-process
6:54PM INF service start impl=multiAppConn module=proxy msg={}
6:54PM INF service start connection=query impl=localClient module=abci-client msg={}
6:54PM INF service start connection=snapshot impl=localClient module=abci-client msg={}
6:54PM INF service start connection=mempool impl=localClient module=abci-client msg={}
6:54PM INF service start connection=consensus impl=localClient module=abci-client msg={}
6:54PM INF service start impl=EventBus module=events msg={}
6:54PM INF service start impl=PubSub module=pubsub msg={}
6:54PM INF service start impl=IndexerService module=txindex msg={}
6:54PM INF ABCI Handshake App Info hash= height=0 module=consensus protocol-version=0 software-version=v0.3.13.37
6:54PM INF ABCI Replay Blocks appHeight=0 module=consensus stateHeight=0 storeHeight=0
panic: unknown field "dapp_liquidation_threshold" in types.NetworkProperties

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/codec.(*ProtoCodec).MustUnmarshalJSON(0x24264f0?, {0xc000d41900?, 0x7fdd34539ff8?, 0xc000dc1f90?}, {0x242ad28?, 0xc00106bd10?})
	/home/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.10/codec/proto_codec.go:178 +0x45
github.com/KiraCore/sekai/x/gov.AppModule.InitGenesis({{}, {{_, _}, {_, _}, {_, _}, {_}}}, {{0x243b300, 0xc000134020}, ...}, ...)
	/__w/sekai/sekai/x/gov/module.go:90 +0xc2
github.com/cosmos/cosmos-sdk/types/module.(*Manager).InitGenesis(_, {{0x243b300, 0xc000134020}, {0x2448280, 0xc000133b80}, {{0x0, 0x0}, {0xc00053ed00, 0xa}, 0x0, ...}, ...}, ...)
	/home/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.10/types/module/module.go:327 +0x29d
github.com/KiraCore/sekai/app.(*SekaiApp).InitChainer(_, {{0x243b300, 0xc000134020}, {0x2448280, 0xc000133b80}, {{0x0, 0x0}, {0xc00053ed00, 0xa}, 0x0, ...}, ...}, ...)
	/__w/sekai/sekai/app/app.go:545 +0x137
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).InitChain(0xc0002948c0, {{0x9878ec1, 0xedbe822bb, 0x0}, {0xc00053ed00, 0xa}, 0xc00121c700, {0x32432b8, 0x0, 0x0}, ...})
	/home/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.10/baseapp/abci.go:63 +0x455
github.com/tendermint/tendermint/abci/client.(*localClient).InitChainSync(0xc000201aa0, {{0x9878ec1, 0xedbe822bb, 0x0}, {0xc00053ed00, 0xa}, 0xc00121c700, {0x32432b8, 0x0, 0x0}, ...})
	/home/go/pkg/mod/github.com/tendermint/tendermint@v0.34.22/abci/client/local_client.go:272 +0x118
github.com/tendermint/tendermint/proxy.(*appConnConsensus).InitChainSync(0x0?, {{0x9878ec1, 0xedbe822bb, 0x0}, {0xc00053ed00, 0xa}, 0xc00121c700, {0x32432b8, 0x0, 0x0}, ...})
	/home/go/pkg/mod/github.com/tendermint/tendermint@v0.34.22/proxy/app_conn.go:77 +0x55
github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(_, {{{0xb, 0x0}, {0x1b44444, 0x7}}, {0xc00053ed00, 0xa}, 0x1, 0x0, {{0x0, ...}, ...}, ...}, ...)
	/home/go/pkg/mod/github.com/tendermint/tendermint@v0.34.22/consensus/replay.go:319 +0xd78
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc000d5fdf0, {0x24488b8, 0xc0000c75f0})
	/home/go/pkg/mod/github.com/tendermint/tendermint@v0.34.22/consensus/replay.go:268 +0x3c8
github.com/tendermint/tendermint/node.doHandshake({_, _}, {{{0xb, 0x0}, {0x1b44444, 0x7}}, {0xc00053ed00, 0xa}, 0x1, 0x0, ...}, ...)
	/home/go/pkg/mod/github.com/tendermint/tendermint@v0.34.22/node/node.go:330 +0x1b8
github.com/tendermint/tendermint/node.NewNode(0xc00104d7c0, {0x24383a8, 0xc001213cc0}, 0xc001084460, {0x2421240, 0xc000127fc8}, 0x0?, 0x0?, 0xc0010847c0, {0x243cb80, ...}, ...)
	/home/go/pkg/mod/github.com/tendermint/tendermint@v0.34.22/node/node.go:778 +0x597
github.com/cosmos/cosmos-sdk/server.startInProcess(_, {{0x0, 0x0, 0x0}, {0x244f0f0, 0xc0011f79e0}, {0x0, 0x0}, {0x2440af8, 0xc001066370}, ...}, ...)
	/home/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.10/server/start.go:280 +0x7db
github.com/cosmos/cosmos-sdk/server.StartCmd.func2(0xc00109d900?, {0xc0010cbba0?, 0x0?, 0x2?})
	/home/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.10/server/start.go:128 +0x169
github.com/spf13/cobra.(*Command).execute(0xc00109d900, {0xc0010cbb80, 0x2, 0x2})
	/home/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:872 +0x694
github.com/spf13/cobra.(*Command).ExecuteC(0xc001004280)
	/home/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
	/home/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	/home/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:911
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0x0?, {0xc00100ddd0, 0xd})
	/home/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.10/server/cmd/execute.go:36 +0x1eb
main.main()
	/__w/sekai/sekai/cmd/sekaid/main.go:185 +0x31
+ EXIT_CODE=2
+ set +x
ERROR: SEKAID process failed with the exit code 2
+ echoWarn 'WARNING: validator is still being configured, please wait ...'
+ echo -e '\e[0m\e[33;1mWARNING: validator is still being configured, please wait ...\e[0m'

```

**Comment by jgo121** [comment]
Is this issue resolved? I think it's related to issue on network upgrade for not setting the genesis values accurately
